A/A/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', 'home'))
]

A/home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('<int:pk>/', views.Home.as_view(), name='home'),
]

A/home/models.py
from django.db import models


class Car(models.Model):
    name = models.CharField(max_length=100)
    owner = models.CharField(max_length=100)
    year = models.PositiveSmallIntegerField()

    def __str__(self):
        return self.name

A/home/forms.py
from django import forms
from .models import Car


class CarCreateForm(forms.ModelForm):
    class Meta:
        model = Car
        fields = '__all__'

A/home/views.py
from .models import Car
from .serializers import CarSerializer
from rest_framework.response import Response
from rest_framework.generics import GenericAPIView, RetrieveDestroyAPIView
from rest_framework.mixins import RetrieveModelMixin, DestroyModelMixin


# class Home(RetrieveModelMixin, DestroyModelMixin, GenericAPIView):
#     serializer_class = CarSerializer
#     queryset = Car.objects.all()
#
#     def retrieve(self, request, *args, **kwargs):
#         instance = self.get_object()
#         if instance.name == 'Nisan':
#             return Response('Sorry.....')
#         serializer = self.get_serializer(instance)
#         return Response(serializer.data)
#
#     def get(self, request, *args, **kwargs):
#         return self.retrieve(request, *args, **kwargs)
#
#     def delete(self, request, *args, **kwargs):
#         return self.delete(request, *args, **kwargs)


class Home(RetrieveDestroyAPIView):
    serializer_class = CarSerializer
    queryset = Car.objects.all()

    def retrieve(self, request, *args, **kwargs):
        instance = self.get_object()
        if instance.name == 'Nisan':
            return Response('Sorry.....')
        serializer = self.get_serializer(instance)
        return Response(serializer.data)

A/home/templates/home/create.html
{% extends 'base.html' %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create">
</form>
{% endblock %}

A/home/templates/home/home.html
{% extends 'base.html' %}

{% block content %}
<h3 class="text-center">HOME</h3>
{% for car in cars %}
<p class="text-center">{{ car.name }}</p>
{% endfor %}
{% endblock %}

A/home/templates/home/update.html
{% extends 'base.html' %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">

</form>
{% endblock %}

A/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Online Shop</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/base_style.css' %}">
    {% block extra_headers %} {% endblock %}
</head>

<body>
{% include 'inc/navbar.html' %}
<div class="jumbotron">
    {% include 'inc/messages.html' %}
    {% block content %}{% endblock %}
</div>

</body>

</html>

A/templates/inc/messages.html
{% if messages %}
{% for message in messages %}
<p class="alert alert-{{ message.tags }}">{{ message }}</p>
{% endfor %}
{% endif %}

A/templates/inc/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
    <div class="container-fluid">
        <div class="navbar-nav">
            <a class="nav-link active" aria-current="page" href="{% url 'home:home' %}">Home</a>
        </div>
    </div>
</nav>

A/templates/method_not_allowed.html
{% extends 'base.html' %}

{% block content %}
<h3 class="text-center">Method not allowed</h3>
<p class="text-center">{{ request.method }} is not allowed</p>
{% endblock %}